# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

gem 'activesupport'
gem 'actionmailer'

gem 'sinatra', github: 'sinatra/sinatra'

gem 'rake'

gem 'byebug'

gem 'mailcatcher'